version: "3.7"

services:
    nginx:
        container_name: ${APP_NAME}_nginx
        build:
            context: ./.docker/development/nginx
            dockerfile: nginx.Dockerfile
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
            - "443:443"

    php-fpm:
        container_name: ${APP_NAME}_php-fpm
        build:
            context: ./.docker/development/php-fpm
            dockerfile: php-fpm.Dockerfile
        volumes:
            - ./:/app
    db:
        container_name: ${APP_NAME}_db
        image: postgres:13
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - ./.docker/db/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    redis:
        container_name: ${APP_NAME}_redis
        image: redis
        ports:
            - "6379:6379"
